config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put 'like', to: 'posts#upvote'
      put 'dislike', to: 'posts#downvote'
    end
    resources :comments
  end

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    acts_as_votable
    belongs_to :user
    has_attached_file :image, styles: { medium: "700x500>", thumb: "350x250>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.build(comment_params)
        @comment.user = current_user
        @comment.save
        redirect_to @post
    end

    private
        def comment_params
            params.require(:comment).permit(:comment, :user_id)
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @posts = Post.all.order("created_at desc")
    end

    def new
        @post = current_user.posts.build
    end

    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            redirect_to @post, notify: "Record saved successfully."
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @post.update(post_params)
            redirect_to @post, notify: "Record updated successfully."
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @post.destroy
        redirect_to root_path, notify: "Record saved successfully."
    end

    def upvote
        @post.upvote by current_user
        redirect_to root_path
    end

    def downvote
        @post.downvote by current_user
        redirect_to root_path
    end

    private
        def find_post
            @post = Post.find(params[:id])
        end

        def post_params
            params.require(:post).permit(:title, :link, :description, :image)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment    
    %p.username= comment.user.name
    %p.content= comment.comment

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
    = f.input :comment, label: "Reply to thread"
    = f.button :submit, class: "button"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Muse
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
  %body
    %header
      .wrapper.clearfix
        #logo= link_to "Muse", root_path
        %nav
          - if user_signed_in?
            = link_to current_user.name, edit_user_registration_path
            = link_to "Add new Inspiration", new_post_path
          - else
            = link_to "Sign In", new_user_session_path, class: "button"
            = link_to "Sign Up", new_user_registration_path, class: "button"
    %p.notice= notice
    %p.alert= alert
    .wrapper
      = yield

app/views/posts/_comment_form.html.haml
= simple_form_for([@post, @post.comment.build]) do |f|
    = f.input :comment, label: "Reply to thread"
    = f.submit, class: "button"

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
    = f.input :image
    = f.input :title
    = f.input :link
    = f.input :description

    = f.submit
= link_to "Home", root_path

app/views/posts/edit.html.haml
%h2 Edit an Inspiration

= render 'form'

app/views/posts/index.html.haml
- if user_signed_in?
    %p#intro
        Hello
        = current_user.name
        %br/
        %span
            Share your inspiration and see what's inspiring others.
-else
    %p#intro
        What's your muse?
        %br/
        %span
            Share your inspiration and see what's inspiring others.    
#posts
    - @posts.each do |post|
        .post
            .post_image
                = link_to (image_tag post.image.url(:thumb)), post
            .post_content
                .title
                    %h2= link_to post.title, post
                .data.clearfix
                    %p.username
                        Shared By
                        = post.user.name
                    %p.buttons
                        %span
                            %i.fa.fa-comments-o
                                = post.comments.count
                        %span
                            %i.fa.fa-thumbs-o-up
                                = post.get_upvotes.count

app/views/posts/new.html.haml
%h2 Add new Inspiration

= render 'form'

app/views/posts/show.html.haml
#post_show
    %h1= @post.title
    %p.username
        Share by
        = @post.user.name
        about
        = time_ago_in_words(@post.created_at)
    .clearfix
        .post_image_description
            = image_tag @post.image.url(:medium)
            .description= simple_format(@post.description)
        .post_data
            = link_to "Visit Link", @post.link, class: "button"
            = link_to like_post_path(@post), method: :put, class: "data" do
                %i.fa.fa-thumbs-o-up
                = pluralize(@post.get_upvotes.size, "Like")
            = link_to dislike_post_path(@post), method: :put, class: "data" do
                %i.fa.fa-thumbs-o-down
                = pluralize(@post.get_downvotes.size, "Dislike")
            %p.data
                %i.fa.fa-comments
                = pluralize(@post.comments.count, "Comment")
            - if @post.user == current_user
                = link_to "Edit", edit_post_path(@post), class: "data"
                = link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure to delete?" }, class: "data"
        #random_post
            %h3 Random Inspiration
            .post
                .post_image
                    
#comments
    %h2.comment_count=pluralize(@post.comments.count, "Comment")
    = render @post.comments
    = render 'comments/form'

= link_to "Home", root_path